### ISSUE TITLE
Why do the table names need to be separated by a dot?

### ISSUE THREAD

**Issue by pkpraveen603** [usedatabrew/pglogicalstream#4]
The table names have been given a pre determined naming convention which feels like a bug
https://github.com/usedatabrew/pglogicalstream/blob/main/logical_stream.go#L98
Also is it not possible to stream all changes instead of specifying the full schema of the table we want to stream the changes for? That feature would be amazing

**Comment by le-vlad** [comment]
Hey @pkpraveen603 
Table separation by a dot is done due to the fact you may need to stream tables from different schemas.  But I'll take a closer look.

What do you mean by saying you want to stream all changes instead of specifying schema? Do you just want to receive raw table data as JSON or something?

As we use Apache Arrow for data structuring down the pipeline (when importing this lib) we need to be aware of the structure of the DataFrame. That's the reason we ask you to provide the entire schema here.
